### ISSUE TITLE
Change step pulse length in the code?

### ISSUE THREAD

**Issue by Totte1210** [rekursiv/stepperature#1]
Hi,

Where can I change the step pulse length in the code?

Best regards

Thorsten

**Comment by rekursiv** [comment]
Hi,

You'll find the code to bring the step output low after it has been triggered starting on line 315.  The comment above it reads "reset prev step."  To make the pulse stay high longer, you'll have to delay what happens here without actually pausing in the loop.  The loop gets triggered at a consistent rate, so watching a counter and calling "stepReset()" after x number of loops go by is one option.  You could use ticksSinceLastStep perhaps?

Hope this helps,
Aaron
